from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.orm import Session
from database_session import access_db

router = APIRouter(
    prefix="/books",
    tags=["books"]
)

class Book(BaseModel):
    book_id: int = Field(validation_alias="id")  # DB column is 'id'
    title: str
    author: str
    category: str
    isBorrowed: bool
    borrowedBy: str
    model_config = {"from_attributes": True}

class BookCreate(BaseModel):  # for POST — id is generated by SQLite
    title: str
    author: str
    category: str

class BookUpdate(BaseModel):
    title: str | None = None
    author: str | None = None
    category: str | None = None
    isBorrowed: bool | None = None
    borrowedBy: str | None = None


db_engine, table = access_db('books', 'books_table')


@router.get("/", response_model=list[Book], status_code=status.HTTP_200_OK)
def get_books(
    title: str | None = None,
    author: str | None = None,
    year: int | None = None,
    isBorrowed: bool | None = None
):
    with Session(db_engine) as session:
        query = select(table)

        if title:
            query = query.where(table.title.ilike(f"%{title}%"))
        if author:
            query = query.where(table.author == author)
        if year:
            query = query.where(table.year == year)
        if isBorrowed:
            query = query.where(table.isBorrowed == false)
        return session.scalars(query).all()


@router.get("/{book_id}", response_model=Book, status_code=status.HTTP_200_OK)
def one_book(book_id: int):
    with Session(db_engine) as session:
        book = session.get(table, book_id)
        if not book:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Book not found")
        return book

@router.post("/", response_model=Book, status_code=status.HTTP_201_CREATED)
def insert_book(book: BookCreate):
    with Session(db_engine) as session:
        try:
            new_book = table(
                title=book.title,
                author=book.author,
                category=book.category,
            )
            session.add(new_book)
            session.commit()
            session.refresh(new_book)  # loads the generated id
            return new_book
        except Exception as e:
            session.rollback()
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))

@router.delete("/{book_id}", status_code=status.HTTP_200_OK)
def delete_book(book_id: int):
    with Session(db_engine) as session:
        book = session.get(table, book_id)
        if not book:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Book not found")

        session.delete(book)
        session.commit()
        return {"message": f"Book {book_id} deleted"}


@router.patch("/{book_id}", response_model=Book)
def update_book(book_id: int, payload: BookUpdate):
    with Session(db_engine) as session:
        book = session.get(table, book_id)
        if not book:
            raise HTTPException(404, "Book not found")
        for field, value in payload.model_dump(exclude_unset=True).items():
            setattr(book, field, value)
        session.commit()
        session.refresh(book)
        return book