from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.orm import Session
from database_session import access_db

router = APIRouter(
    prefix="/members",
    tags=["members"]
)

class Member(BaseModel):
    member_id: int = Field(validation_alias="id")  # DB column is 'id'
    memberName: str
    booksBorrowed: list[str] | None = None # NULL when no books currently borrowed
    borrowHistory: list[str] | None = None  # NULL when no books have been borrowed
    model_config = {"from_attributes": True}

class memberCreate(BaseModel): # for POST — id is generated by SQLite
    memberName: str

class memberUpdate(BaseModel):
    memberName: str | None = None
    booksBorrowed: list[str] | None = None  
    borrowHistory: list[str] | None = None


db_engine, table = access_db('members', 'members_table')


@router.get("/", response_model=list[Member], status_code=status.HTTP_200_OK)
def get_members(memberName: str | None = None):
    with Session(db_engine) as session:
        query = select(table)

        if memberName:
            query = query.where(table.memberName.ilike(f"%{memberName}%"))
        return session.scalars(query).all()


@router.get("/{member_id}", response_model=Member, status_code=status.HTTP_200_OK)
def one_member(member_id: int):
    with Session(db_engine) as session:
        member = session.get(table, member_id)
        if not member:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Member not found")
        return member


@router.post("/", response_model=Member, status_code=status.HTTP_201_CREATED)
def insert_member(member: memberCreate):
    with Session(db_engine) as session:
        try:
            new_member = table(memberName=member.memberName)
            session.add(new_member)
            session.commit()
            session.refresh(new_member)
            return new_member
        except Exception as e:
            session.rollback()
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))


@router.delete("/{member_id}", status_code=status.HTTP_200_OK)
def delete_member(member_id: int):
    with Session(db_engine) as session:
        member = session.get(table, member_id)
        if not member:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Member not found")

        session.delete(member)
        session.commit()
        return {"message": f"Member {member_id} deleted"}


@router.patch("/{member_id}", response_model=Member)
def update_member(member_id: int, payload: memberUpdate):
    with Session(db_engine) as session:
        member = session.get(table, member_id)
        if not member:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Member not found")
        for field, value in payload.model_dump(exclude_unset=True).items():
            setattr(member, field, value)
        session.commit()
        session.refresh(member)
        return member