-- =====================================================================
--  Web Systems and Technologies  ·  Week 9 Challenge
--  THE CAMPUS LIBRARY — STUDENT STARTER
-- ---------------------------------------------------------------------
--  This is the single, flawed table you inherited. Load it into a
--  PostgreSQL database, look at it, and use it for Part A (Analyze).
--  You will redesign it in Part B — do NOT edit this file to "fix" it.
--
--  Load it with:   psql -d library_challenge -f 01_flawed_database.sql
-- =====================================================================
DROP TABLE IF EXISTS circulation;

CREATE TABLE circulation (
    member_id      INTEGER,
    member_name    TEXT,
    member_email   TEXT,
    isbn           TEXT,
    title          TEXT,
    genre          TEXT,
    authors        TEXT,   -- multivalued!  e.g. 'Cruz; Santos'
    author_emails  TEXT,   -- multivalued, kept parallel to authors
    borrowed_on    DATE,
    due_on         DATE
);

INSERT INTO circulation
    (member_id, member_name, member_email, isbn, title, genre,
     authors, author_emails, borrowed_on, due_on)
VALUES
    (1, 'Ana Cruz', 'ana@u.edu', '978-1', 'Web Systems', 'Tech',
     'Cruz; Santos', 'cruz@p.edu; santos@p.edu', '2026-06-01', '2026-06-15'),
    (1, 'Ana Cruz', 'ana@u.edu', '978-2', 'Databases', 'Tech',
     'Reyes', 'reyes@p.edu', '2026-06-03', '2026-06-17'),
    (2, 'Ben Lim', 'ben@u.edu', '978-1', 'Web Systems', 'Tech',
     'Cruz; Santos', 'cruz@p.edu; santos@p.edu', '2026-06-05', '2026-06-19'),
    (2, 'Ben Lim', 'ben@u.edu', '978-3', 'Networks', 'Tech',
     'Reyes', 'reyes@p.edu', '2026-06-08', '2026-06-22'),
    (3, 'Cy Dela Cruz', 'cy@u.edu', '978-2', 'Databases', 'Tech',
     'Reyes', 'reyes@p.edu', '2026-06-09', '2026-06-23');

-- Look at what you inherited:
--   SELECT * FROM circulation;
--
-- Notice as you read Part A:
--   * 'Ana Cruz' and her email repeat on every book she borrows
--   * 'Web Systems' and its authors repeat for every member who borrows it
--   * the 'authors' column holds more than one value in a single cell
--   * you cannot record a book nobody has borrowed yet — there is no row for it
